spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/week10
    username: study
    password: study1234
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: SECRET

server:
  servlet:
    encoding:
      force-response: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: SECRET
